### ISSUE TITLE
grpcio >= 1.46.3 is broken for fork-based GRPC client calls

### ISSUE THREAD

**Issue by jnbolito** [conda-forge/grpc-cpp-feedstock#187]
Hi, I use grpcio (installed from a Python 3.7 conda environment) with multiple google cloud  SDK libraries. It seems from 1.46.3 onwards (ever since you merged the feedstocks it seems), all of our post-fork Google SDK API calls, which rely on grpc calls underneath, no longer work. It seems that the underlying process simply hangs. This behaviour is similar to the one observed when one doesn't set the env vars GRPC_ENABLE_FORK_SUPPORT and GRPC_POLL_STRATEGY. 

The reason I believe this looks like an issue with the conda package is because I am unable to reproduce the problem when using the corresponding pypi packages. Do you have an idea of what the issue might be or what I might be doing wrong?

Thanks in advance! 😄 

Environment:
Conda version: 4.12
Platform: Linux x86-64
Python version: 3.7.12

**Comment by h-vetinari** [comment]
Hey @jnbolito; sorry for the long delay on this. Do you still have this issue with more recent grpc builds?

**Comment by h-vetinari** [comment]
Closing this as stale. Please open a new issue if you still encounter problems.
