### ISSUE TITLE
run_export doesn't account for abseil version

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/grpc-cpp-feedstock#212]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

On windows builds it looks like this recipe static links abseil but then the run export only exports a minor version of the package without ensuring that it gets the same abseil version. This leads to missing symbols, for example from a recent arrow-cpp build: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=551543&view=logs&jobId=f15996c2-5e30-5466-ec4d-2c68bcfb4db9&j=f15996c2-5e30-5466-ec4d-2c68bcfb4db9&t=f8cd7f8c-ad12-57b1-4cd6-c2be466b37a3

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by kkraus14** [comment]
cc @hmaarrfk

**Comment by h-vetinari** [comment]
Thanks for the report, and sorry for the breakage. Indeed, the static builds on abseil don't have a run export. This was my handiwork, though in my defense, other static builds don't have run exports either (e.g. [zstd](https://github.com/conda-forge/zstd-feedstock/blob/main/recipe/meta.yaml#L79-L82)).

It maybe something about the build instructions on this feedstock, but my understanding of static builds would have been that all required symbols should be absorbed into the build here, so I don't quite get where the run-dependence comes from (conceptually).

**Comment by kkraus14** [comment]
Apologies, this issue is incorrect as what I'm running into is a mismatch between versions of `grpc-cpp` in the build and host sections as opposed to the host and run sections. Will close this and open a new issue if needed.
