### ISSUE TITLE
minor request

### ISSUE THREAD

**Issue by ngam** [conda-forge/grpc-cpp-feedstock#221]
### Comment:

rebuild: grpc-cpp 1.46.4 with abseil 20211102.0

motivation: `mamba install grpc-cpp==1.46.4` yields:

```
package tensorflow-base-2.9.1-cpu_py310h048a3e3_0 requires abseil-cpp >=20211102.0,<20211102.1.0a0, but none of the providers can be installed
```

These pins are crazy wild... :tear

**Comment by h-vetinari** [comment]
There are no builds of 1.46.4 for older abseil. Any reason you cannot stay on 1.46.3?
