### ISSUE TITLE
It seems that `grpc-cpp 1.48.0 h1737d0c_2` package is missed on windows

### ISSUE THREAD

**Issue by anmyachev** [conda-forge/grpc-cpp-feedstock#261]
Mamba output on windows:
```cmd
  Encountered problems while solving:
    - nothing provides grpc-cpp 1.48.0 h1737d0c_2 needed by grpcio-1.48.0-py310h07b4452_2
```

cc @h-vetinari

**Comment by h-vetinari** [comment]
Yes, it's been marked broken (currently on [page 8](https://anaconda.org/conda-forge/grpc-cpp/files?page=8)) and shouldn't be used. There's been a lot of 1.48.x builds afterwards that should serve your needs. Sorry for the trouble

**Comment by anmyachev** [comment]
> Yes, it's been marked broken (currently on [page 8](https://anaconda.org/conda-forge/grpc-cpp/files?page=8)) and shouldn't be used. There's been a lot of 1.48.x builds afterwards that should serve your needs. Sorry for the trouble

ok for me, thanks @h-vetinari!
