### ISSUE TITLE
1.58 packages do not work with ray

### ISSUE THREAD

**Issue by mattip** [conda-forge/grpc-cpp-feedstock#343]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

See https://github.com/conda-forge/ray-packages-feedstock/issues/136. It seems grpcio 1.58.2 is broken? Are there projects that are using it successfully? There is some debate where the interaction problem is: in ray (which internally links to its own verison of grpcio) or in this feedstock.

### Installed packages

```shell
see the ray/ray issue
```

### Environment info

```shell
see the ray/ray issue
```

**Comment by h-vetinari** [comment]
It's fine to refer to another issue (I've corrected the link), but you should at least distill a summary of the issues and the reproducer.

**Comment by h-vetinari** [comment]
> See [conda-forge/ray-packages-feedstock#136](https://github.com/conda-forge/ray-packages-feedstock/issues/136). It seems grpcio 1.58.2 is broken? Are there projects that are using it successfully?

We did have a migration for 1.58 that worked fine, but for several months now pretty much all of conda-forge has been on 1.59. You might have to copy https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/libgrpc159_libprotobuf4244.yaml under `.ci_support/migrations` and rerender, but I guess it's also time to close the migration soon.

**Comment by mattip** [comment]
What combination of ray 2.9.0 and jax both resolves and is functional?

**Comment by timkpaine** [comment]
I think this issue can be closed, we're pretty aware of the issues in ray at this point and working through them as we go
